name: License Compliance Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  snyk-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14' # Node.js 버전은 필요에 따라 변경

      - name: Install Snyk CLI
        run: npm install -g snyk

      - name: Run Snyk License Compliance Check
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        run: snyk test --all-projects --severity-threshold=medium --json-file-output=snyk-results.json

      - name: Upload Snyk Results
        uses: actions/upload-artifact@v3
        with:
          name: snyk-license-results
          path: snyk-results.json
